"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface Props {
  asset?: string;
  timeframe?: string;
  signal?: string;
  entry?: string;
  stopLoss?: string;
  takeProfit1?: string;
  takeProfit2?: string;
  confidence?: number;
  isPro: boolean;
}

function generatePineScript(p: Props): string {
  const asset = p.asset ?? "ASSET";
  const tf    = p.timeframe ?? "";
  const dir   = (p.signal ?? "").toUpperCase() === "SHORT" ? "SELL" : "BUY";
  const entry = p.entry    ?? "0";
  const sl    = p.stopLoss ?? "0";
  const tp1   = parseFloat(p.takeProfit1 ?? "0") || 0;
  const conf  = p.confidence ?? 0;
  const isBuy = dir === "BUY";
  const entryF = parseFloat(entry) || 0;
  const tp2 = tp1
    ? isBuy  ? (tp1 + (tp1 - entryF)).toFixed(2)
             : (tp1 - (entryF - tp1)).toFixed(2)
    : "0";
  const dirColor = isBuy ? "color.lime" : "color.red";
  const dirEmoji = isBuy ? "🟢" : "🔴";

  return `//@version=5
// ═══════════════════════════════════════════════════════
// ChartIQ AI Signal — ${asset}${tf ? ` · ${tf}` : ""}
// Generated by ChartIQ AI — trade-edge-ai.vercel.app
// Signal: ${dir} | Confidence: ${conf}%
// ═══════════════════════════════════════════════════════
indicator("ChartIQ Signal", overlay=true,
     max_lines_count=10, max_labels_count=10)

// ── Signal Levels ────────────────────────────────────
float entry_price = ${entry}
float sl_price    = ${sl}
float tp1_price   = ${tp1.toFixed(2)}
float tp2_price   = ${tp2}

// ── Horizontal Lines ─────────────────────────────────
hline(entry_price, "Entry: ${entry}",   color=color.white,  linestyle=hline.style_solid,  linewidth=2)
hline(sl_price,    "SL: ${sl}",         color=color.red,    linestyle=hline.style_dashed, linewidth=1)
hline(tp1_price,   "TP1: ${tp1.toFixed(2)}", color=color.lime,   linestyle=hline.style_dashed, linewidth=1)
hline(tp2_price,   "TP2: ${tp2}",  color=color.green,  linestyle=hline.style_dashed, linewidth=1)

// ── Entry Zone Background ─────────────────────────────
float zone_hi = math.max(entry_price, sl_price)
float zone_lo = math.min(entry_price, sl_price)
bgcolor(close >= zone_lo and close <= zone_hi
     ? color.new(color.white, 90) : na, title="Entry Zone")

// ── Signal Label ──────────────────────────────────────
if barstate.islast
    label.new(bar_index + 2, entry_price,
        text="${dirEmoji} ${dir} ${conf}%\\n📍 Entry: ${entry}\\n🛑 SL:    ${sl}\\n🎯 TP1:  ${tp1.toFixed(2)}\\n🎯 TP2:  ${tp2}",
        color=color.new(${dirColor}, 10),
        textcolor=color.white,
        style=label.style_label_left,
        size=size.normal)
`;
}

export default function PineScriptExport(props: Props) {
  const [open,   setOpen]   = useState(false);
  const [copied, setCopied] = useState(false);

  const script = generatePineScript(props);

  async function handleCopy() {
    await navigator.clipboard.writeText(script);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  }

  if (!props.isPro) {
    return (
      <motion.div
        initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 1.7, duration: 0.4 }}
        className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-4"
      >
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
              <path d="M2 3.5h10M2 7h6M2 10.5h8" stroke="#4b5563" strokeWidth="1.3" strokeLinecap="round"/>
            </svg>
            <span className="text-xs font-semibold text-[#4b5563]">Export to TradingView</span>
          </div>
          <span className="font-dm-mono text-[9px] font-bold tracking-widest px-2 py-0.5 rounded-full"
            style={{ background: "rgba(0,230,118,0.1)", color: "#00e676", border: "1px solid rgba(0,230,118,0.2)" }}>
            PRO
          </span>
        </div>
      </motion.div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 1.7, duration: 0.4 }}
      className="rounded-2xl border overflow-hidden"
      style={{
        borderColor: open ? "rgba(0,230,118,0.22)" : "rgba(255,255,255,0.07)",
        background: "#090d12",
      }}
    >
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-4 py-3.5 hover:bg-white/[0.02] transition-colors"
      >
        <div className="flex items-center gap-2.5">
          <svg width="15" height="15" viewBox="0 0 15 15" fill="none">
            <path d="M2 3.5h11M2 7.5h7M2 11.5h9" stroke="#00e676" strokeWidth="1.35" strokeLinecap="round"/>
          </svg>
          <span className="text-sm font-semibold text-white">Export to TradingView</span>
          <span className="font-dm-mono text-[9px] font-bold tracking-widest px-2 py-0.5 rounded-full"
            style={{ background: "rgba(0,230,118,0.1)", color: "#00e676", border: "1px solid rgba(0,230,118,0.18)" }}>
            PINE SCRIPT
          </span>
        </div>
        <svg width="12" height="12" viewBox="0 0 12 12" fill="none"
          className={`transition-transform duration-200 ${open ? "rotate-180" : ""}`}>
          <path d="M2 4l4 4 4-4" stroke="#6b7280" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      </button>

      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.22, ease: [0.16, 1, 0.3, 1] }}
            className="overflow-hidden"
          >
            <div className="px-4 pb-4 space-y-3 border-t border-white/[0.05]">
              <div className="relative rounded-xl overflow-hidden mt-3"
                style={{ background: "#06080f", border: "1px solid rgba(255,255,255,0.06)" }}>
                <pre className="text-[10.5px] font-dm-mono text-[#7c93b0] p-4 overflow-x-auto leading-[1.65]"
                  style={{ maxHeight: "220px" }}>
                  {script}
                </pre>
              </div>

              <div className="grid grid-cols-2 gap-2">
                <button
                  onClick={handleCopy}
                  className="flex items-center justify-center gap-1.5 py-2.5 rounded-xl text-xs font-bold transition-all hover:-translate-y-0.5"
                  style={copied
                    ? { background: "rgba(0,230,118,0.12)", color: "#00e676", border: "1px solid rgba(0,230,118,0.3)" }
                    : { background: "#00e676", color: "#080a10" }}
                >
                  {copied ? (
                    <><svg width="11" height="11" viewBox="0 0 11 11" fill="none"><path d="M2 5.5l2 2.5L9 2.5" stroke="#00e676" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>Copied!</>
                  ) : (
                    <><svg width="11" height="11" viewBox="0 0 11 11" fill="none"><rect x="3.5" y="3.5" width="6.5" height="6.5" rx="1.2" stroke="currentColor" strokeWidth="1.1"/><path d="M3.5 7.5H2.5A1.2 1.2 0 011.3 6.3V3a1.2 1.2 0 011.2-1.2H5.7A1.2 1.2 0 016.9 3v1" stroke="currentColor" strokeWidth="1.1" strokeLinecap="round"/></svg>Copy Script</>
                  )}
                </button>
                <a href="https://tradingview.com" target="_blank" rel="noopener noreferrer"
                  className="flex items-center justify-center gap-1.5 py-2.5 rounded-xl text-xs font-bold transition-all hover:-translate-y-0.5"
                  style={{ background: "rgba(33,150,243,0.1)", color: "#42a5f5", border: "1px solid rgba(33,150,243,0.22)" }}>
                  <svg width="11" height="11" viewBox="0 0 11 11" fill="none">
                    <path d="M9 2L2 9M9 2H5M9 2V6" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  Open TradingView
                </a>
              </div>

              <div className="rounded-xl px-3 py-2 font-dm-mono text-[10px] text-[#6b7280]"
                style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.04)" }}>
                Pine Script Editor → New → Paste → Add to chart
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
